 #Config file for https://travis-ci.org/
language: php

# Define the php versions against we want to test our code
php:
- 7.1
- 7.2


services:
- mysql


before_script: composer require atoum/atoum
script: vendor/bin/atoum

notifications:
  slack: comp-4110project:keEH1mL1AkgTvZVQ8jfcahKU
  
  addons:
  browserstack:
    username: sanadali2
    access_key: w7uyBxPyjHm88H7AEEeL
    
  
